name: 'Build Changelog'
description: 'Build changelog to be attached to the body of a GitHub release'
inputs:
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
  GITHUB_TOKEN:
    description: 'The value of the secret GitHub token'
    required: true
outputs:
  changelog:
    description: 'Markdown string returned using search results'
runs:
  using: 'node12'
  main: 'index.js'
