name: Get all PRs on tag push

on:
  push:
    tags:
      - 'v**-alpha**'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: build_changelog
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          tag_name: ${{ github.ref }}
